Repository apinf/platform, pull requests merged in 2018-05, with the labels that each got.

#3442 Improve 24 h graphs to show hourly data
  apinf_packages/analytics/server/methods.js
  apinf_packages/core/helper_functions/date_range.js
  apinf_packages/core/helper_functions/format_date.js
  apinf_packages/core/lib/i18n/en.i18n.json
  apinf_packages/dashboard/client/analytic/body/body.html
  apinf_packages/dashboard/client/analytic/body/body.js
  apinf_packages/dashboard/client/analytic/header/header.html
  apinf_packages/dashboard/client/analytic/header/header.js
  apinf_packages/dashboard/client/charts/median_response_time/median_response_time.js
  apinf_packages/dashboard/client/charts/requests_number/requests_number.js
  apinf_packages/dashboard/client/charts/requests_over_time/requests_over_time.js
  apinf_packages/dashboard/client/charts/response_time/response_time.js
  apinf_packages/dashboard/client/charts/unique_users/unique_users.js
  apinf_packages/dashboard/client/dashboard.less
  apinf_packages/dashboard/client/date_range_picker/toolbar.html
  apinf_packages/dashboard/client/view/overview/overview.html
  apinf_packages/dashboard/client/view/overview/overview.js
  apinf_packages/dashboard/client/view/view.js
  apinf_packages/dashboard/lib/chart_helpers.js
  apinf_packages/dashboard/lib/histogram_data.js
  apinf_packages/dashboard/lib/status_codes.js
  apinf_packages/dashboard/lib/timeline_chart.js
  apinf_packages/dashboard/lib/total_numbers.js
  apinf_packages/dashboard/lib/trend_helpers.js
  apinf_packages/dashboard/server/manage_data.js
  apinf_packages/dashboard/server/methods.js
  apinf_packages/elasticsearch/server/methods.js
  apinf_packages/proxy_backends/collection/helpers.js
Labels: Ready for review, in progress

#3472 Add a text about No trend (Dashboard page)
  apinf_packages/core/lib/i18n/en.i18n.json
  apinf_packages/dashboard/client/dashboard.less
  apinf_packages/dashboard/client/view/summary_statistics/summary.js
  apinf_packages/dashboard/lib/trend_helpers.js
Labels: in progress

#3474 Changed label for inputting API URL
  apinf_packages/core/lib/i18n/en.i18n.json
Labels: Ready for review

#3493 Integrate account and profile in single page
  apinf_packages/core/client/userMenu.html
  apinf_packages/core/lib/i18n/en.i18n.json
  apinf_packages/settings/client/menu/menu.html
  apinf_packages/users/client/account/account.html
  apinf_packages/users/client/account/account.js
  apinf_packages/users/client/account/autoform.js
  apinf_packages/users/client/profile/profile.html
  apinf_packages/users/client/profile/profile.js
  apinf_packages/users/client/profile/profile.less
  tests/Gate_1/6.profile.robot
Labels: Ready for review
