Repository apinf/platform, pull requests merged in 2018-03, with the labels that each got.

#3433 REST Dashboard: Change "Last 30 days" to 28 days
  apinf_packages/core/lib/i18n/en.i18n.json
  apinf_packages/dashboard/client/date_range_picker/toolbar.html
Labels: Ready for review, in progress

#3430 Show API key instead of email in the table "Most frequent users"
  apinf_packages/core/lib/i18n/en.i18n.json
  apinf_packages/dashboard/client/elasticsearch_queries/most_users.js
  apinf_packages/dashboard/client/tables/frequent_users/users.html
  apinf_packages/dashboard/client/tables/frequent_users/users.js
Labels: Ready for review, in progress

#3381 Feature/internationalize date formatting of charts
  apinf_packages/core/helper_functions/format_date.js
  apinf_packages/dashboard/client/charts/median_response_time/median_response_time.js
  apinf_packages/dashboard/client/charts/requests_number/requests_number.js
  apinf_packages/dashboard/client/charts/requests_over_time/requests_over_time.js
  apinf_packages/dashboard/client/charts/response_time/response_time.js
  apinf_packages/dashboard/client/charts/unique_users/unique_users.js
  apinf_packages/metadata/client/view/metadata.js
Labels: Ready for review, in progress

#3438 Remove possibility to add organisation managers by username
  apinf_packages/organizations/client/managers/list/list.html
  apinf_packages/organizations/server/methods.js
Labels: Ready for review

#3439 Update to latest develop
  apinf_packages/core/helper_functions/format_date.js
  apinf_packages/dashboard/client/charts/median_response_time/median_response_time.js
  apinf_packages/dashboard/client/charts/requests_number/requests_number.js
  apinf_packages/dashboard/client/charts/requests_over_time/requests_over_time.js
  apinf_packages/dashboard/client/charts/response_time/response_time.js
  apinf_packages/dashboard/client/charts/unique_users/unique_users.js
  apinf_packages/metadata/client/view/metadata.js
  apinf_packages/organizations/client/managers/list/list.html
  apinf_packages/organizations/server/methods.js
Labels: in progress

#3446 Fix Eslint errors on the develop branch
  apinf_packages/organizations/server/methods.js
  yarn.lock
Labels: in progress
